# Configuration Zigbee2MQTT pour ZB433 Router

# Exemple de configuration pour le ZB433 Router
# À ajouter dans votre configuration.yaml Zigbee2MQTT

# Device mapping
devices:
  '0x1234567890abcdef':  # Remplacez par l'adresse MAC de votre device
    friendly_name: 'ZB433 Router'
    description: 'ESP32-C6 Zigbee Router pour CAME-24'
    model: 'ZB433-Router'
    vendor: 'Custom'
    supports: 'on/off'
    
    # Endpoints (alignés sur firmware: EP1 et EP2)
    endpoints:
      1:
        friendly_name: 'Portail Principal'
        description: 'Contrôle Portail Principal (CAME-24)'
        cluster: 'on_off'
        state: 'state'
        command: 'set'
        
      2:
        friendly_name: 'Portail Parking'
        description: 'Contrôle Portail Parking (CAME-24)'
        cluster: 'on_off'
        state: 'state'
        command: 'set'

# MQTT Topics (exemple)
topics:
  state: 'zigbee2mqtt/ZB433 Router/{endpoint}/state'
  set: 'zigbee2mqtt/ZB433 Router/{endpoint}/set'
  get: 'zigbee2mqtt/ZB433 Router/{endpoint}/get'

# Attributs manufacturer
manufacturer_attributes:
  0xF001: 'ota_url'
  0xF002: 'device_info'