# Configuration Zigbee2MQTT pour ZB433 Router

# Exemple de configuration pour le ZB433 Router
# À ajouter dans votre configuration.yaml Zigbee2MQTT

# Device mapping
devices:
  '0x1234567890abcdef':  # Remplacez par l'adresse MAC de votre device
    friendly_name: 'ZB433 Router'
    description: 'ESP32-C6 Zigbee Router pour CAME-24'
    model: 'ZB433-Router'
    vendor: 'Custom'
    supports: 'on/off'
    
    # Endpoints
    endpoints:
      10:
        friendly_name: 'Porte A'
        description: 'Contrôle Porte A CAME-24'
        cluster: 'on_off'
        state: 'state'
        command: 'set'
        
      11:
        friendly_name: 'Porte B'
        description: 'Contrôle Porte B CAME-24'
        cluster: 'on_off'
        state: 'state'
        command: 'set'
        
      13:
        friendly_name: 'OTA'
        description: 'Déclenchement mise à jour OTA'
        cluster: 'on_off'
        state: 'state'
        command: 'set'
        
      14:
        friendly_name: 'Factory Reset'
        description: 'Reset complet du device'
        cluster: 'on_off'
        state: 'state'
        command: 'set'

# MQTT Topics
topics:
  state: 'zigbee2mqtt/ZB433 Router/{endpoint}/state'
  set: 'zigbee2mqtt/ZB433 Router/{endpoint}/set'
  get: 'zigbee2mqtt/ZB433 Router/{endpoint}/get'

# Attributs manufacturer
manufacturer_attributes:
  0xF001: 'ota_url'
  0xF002: 'device_info'